[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
# remappings= ["@chainlink/contracts=/lib/chainlink-brownie-contracts/contracts","@solmate/tokens/=lib/solmate/src/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

 
#  /root/foundry-lottery-f24/lib/chainlink-brownie-contracts/contracts/src/v0.8/vrf/dev/VRFConsumerBaseV2Plus.sol